#define IDI_MYICON  131
#define ID_HELP_ABOUT 103
#define ID_FILE_SAVETOFILE 104
#define ID_ENCRYPTION_USEPSWD 106
#define ID_ENCRYPTION_REVERSE 102
#define ID_ENCRYPTION_HIDEPSWD 101
#define ID_FILE_LOADFROMFILE 107
#define ID_ENCRYPTION_FVERSION_CRYPT1 118
#define ID_ENCRYPTION_FVERSION_CRYPT2 119
#define ID_ENCRYPTION_FVERSION_CRYPT3 120
#define ID_ENCRYPTION_FVERSION_CRYPT4 121
#define ID_ENCRYPTION_FVERSION_CRYPT45 122
#define ID_EDIT_CLEAR 108
#define IDD_ABOUT 105
#define IDC_STATIC -1
#define IDC_VER 152
#define IDV_VER "Version 0.5Dev"